name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Vite Project
        run: |
          cd frontend
          npm run build

  deploy:
    needs: build
    runs-on:  windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Deploy to Vercel
        run: |
          echo "Deploying to Vercel..."
          # Add Vercel deployment commands if needed